In [2]:
pip list | grep numpy

numpy                              1.20.3
numpydoc                           1.1.0
Note: you may need to restart the kernel to use updated packages.


In [3]:
pip freeze | grep numpy

numpy @ file:///opt/concourse/worker/volumes/live/9909a8d0-9b8e-44eb-6059-6c668078c029/volume/numpy_and_numpy_base_1626271794641/work
numpydoc @ file:///tmp/build/80754af9/numpydoc_1605117425582/work
Note: you may need to restart the kernel to use updated packages.


In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np

In [6]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',

In [7]:
# create Arrays using numpy
# Create a 1D array

m1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(m1)

[1 2 3 4 5 6 7 8 9]


In [8]:
print(type(m1))

<class 'numpy.ndarray'>


In [9]:
m1.shape()

TypeError: 'tuple' object is not callable

In [10]:
print(m1.shape)

(9,)


In [11]:
m2 = np.array([1, 2, 3, 4])

In [12]:
print(m2.shape)

(4,)


In [15]:
m3 = m2.reshape((1, 4))

In [14]:
print(m2.shape)

(4,)


In [16]:
print(m3.shape)

(1, 4)


In [17]:
m4 = m2.reshape((2, 4))

ValueError: cannot reshape array of size 4 into shape (2,4)

In [19]:
m5 = np.array([[1, 2, 3, 4,]])
m5.shape

(1, 4)

In [20]:
print(type(m5))

<class 'numpy.ndarray'>


In [21]:
m6 = np.array([[1, 2, 3, 4, 5], [2, 4, 6, 7, 8]])

In [22]:
print(m6.shape)

(2, 5)


In [23]:
print(m6)

[[1 2 3 4 5]
 [2 4 6 7 8]]


In [30]:
threedmatrix = np.array([[[2, 3], [5, 6], [7, 8]]])

In [31]:
print(threedmatrix.shape)

(1, 3, 2)


In [42]:
threedmatrix = np.array([[[[2, 3, 4], [5, 6, 7]]], [[5, 6, 7]], [
                        [7, 8, 9]], [[9, 10, 11]], [[12, 13, 14]]])
print(threedmatrix.shape)

(5, 1)


/var/folders/3s/741zy__53cdgvsbv2zvpy2m80000gp/T/ipykernel_38535/4134676505.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  threedmatrix = np.array([[[[2,3,4],[5,6,7]]], [[5,6,7]], [[7,8,9]], [[9,10,11]], [[12,13,14]]])


In [45]:
m3matrix = np.array([[1, 2, 3, 4, 5], [4, 5, 6, 7, 8]])
print(m3matrix)
print(m3matrix.shape)

[[1 2 3 4 5]
 [4 5 6 7 8]]
(2, 5)


In [49]:
m4 = np.arange(0, 10, 2)
print(m4)
print(m4.shape)

[0 2 4 6 8]
(5,)


In [50]:
m4.reshape(5, 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [52]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [54]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [56]:
ones = np.ones((2, 3))
print(ones.shape)

(2, 3)


In [59]:
twos = np.ones((1, 2))
print(twos)
print(twos.shape)

[[1. 1.]]
(1, 2)


In [68]:
# Identity Matrix
i = np.eye(4, 4)
print(i.shape)
print(i)

(4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [89]:
# Attributes of numpy array
matrix = np.array([[1, 2, 3], [4, 5, 6]])

print("Array: \n", matrix)
print("Shape: \n", matrix.shape)
print("Number of dimensiones : \n", matrix.ndim)
print("Size (Number of elements):", matrix.size)
print("Data Type: ", matrix.dtype)
print("Item size (in bytes): ", matrix.itemsize)

Array: 
 [[1 2 3]
 [4 5 6]]
Shape: 
 (2, 3)
Number of dimensiones : 
 2
Size (Number of elements): 6
Data Type:  int64
Item size (in bytes):  8


In [88]:
# Numpy vectorized operations
m1 = np.array([1, 2, 3, 4, 5])
m2 = np.array([10, 20, 30, 40, 50])


print("Addition :", m1 + m2)
print("Subtraction :", m1 - m2)

print("Multiplication :", m1 * m2)
print("Division : ", m1 / m2)

Addition : [11 22 33 44 55]
Subtraction : [ -9 -18 -27 -36 -45]
Multiplication : [ 10  40  90 160 250]
Division :  [0.1 0.1 0.1 0.1 0.1]


In [96]:
# Universal Functions - Functions that apply to entire array

m1 = np.array([1, 2, 3, 4, 5])
print("Square root is:", np.sqrt(m1))

# Exponential
print("Exponential is:", np.exp(m1))

Square root is: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential is: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [142]:
# Array slicing and indexing

m1 = np.array([[1, 2, 3, 4, 5], [4, 6, 7, 8, 9], [6, 10, 11, 9, 10]])
print(m1)

[[ 1  2  3  4  5]
 [ 4  6  7  8  9]
 [ 6 10 11  9 10]]


In [103]:
m1[0]

array([1, 2, 3, 4, 5])

In [104]:
m1[0][2]

3

In [105]:
m1[1][3]

7

In [109]:
m1

array([[ 1,  2,  3,  4,  5],
       [ 4,  5,  6,  7,  8],
       [ 6,  7,  8,  9, 10]])

In [110]:
m1[1:]

array([[ 4,  5,  6,  7,  8],
       [ 6,  7,  8,  9, 10]])

In [115]:
m1[1:, 3:]

array([[ 7,  8],
       [ 9, 10]])

In [116]:
m1[1:, 4:]

array([[ 8],
       [10]])

In [117]:
print(m1)

[[ 1  2  3  4  5]
 [ 4  5  6  7  8]
 [ 6  7  8  9 10]]


In [135]:
m1[0:2, 3:]

array([[4, 5],
       [7, 8]])

In [144]:
print(m1[1:3, 1:3])

[[ 6  7]
 [10 11]]


In [145]:
m1[0, 0] = 100

In [146]:
print(m1)

[[100   2   3   4   5]
 [  4   6   7   8   9]
 [  6  10  11   9  10]]


In [154]:
print(m1[2][3])

9


In [156]:
m1[1:] = 100
print(m1)

[[100   2   3   4   5]
 [100 100 100 100 100]
 [100 100 100 100 100]]


In [162]:
# Statistical Concepts - Normalization
# To have mean of 0 and standard of deviation of 1

# Normalization converting data such a way that mean is equal to 0 and std = 1

data = np.array([1, 2, 3, 4, 5])

# Calculate the mean and standard deviation
mean = np.mean(data)
print(mean)

std_dev = np.std(data)
print(std_dev)

normalized_data = (data - mean) / std_dev
print("normalized data : ", normalized_data)

3.0
1.4142135623730951
normalized data :  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [168]:
mat1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(mat1)
print("Mean ", mean)

# Median
median = np.median(mat1)
print("Median", median)

# Standard Deviation
std_dev = np.std(mat1)
print("Standard Deviation ", std_dev)


# Variance
variance = np.var(mat1)
print("Variance ", variance)

Mean  5.5
Median 5.5
Standard Deviation  2.8722813232690143
Variance  8.25


In [169]:
# Logical operation

data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
data > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [171]:
data[data > 5]

array([ 6,  7,  8,  9, 10])